# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e4ee736adb1e1713e4d681f494985c1611d974b2d6442ca5e70c0907229adb95bca3a233367f7159de4bd9bdb4e346736aa026d36bdfb2037b24508c5e66bc9

test:
  secret_key_base: cdebbc3b6564b2de4de774d95430b11e304b5d5e75a155486ff8626cd3ea6f40659dcf1f212287d58391f57182c3bf2d2f9bc752c79a8785877387c558647f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
